name: Terraform Plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Terraform environment directory (e.g., env/product-a/dev)'
        required: true
        type: string
  pull_request:
    paths:
      - 'env/**'
      - 'modules/**'

env:
  TF_VERSION: '1.5.7'

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure JFrog credentials
        run: |
          mkdir -p ~/.terraform.d
          cat > ~/.terraform.d/credentials.tfrc.json <<EOF
          {
            "credentials": {
              "trialviki.jfrog.io": {
                "token": "${{ secrets.JFROG_ACCESS_TOKEN }}"
              }
            }
          }
          EOF

      - name: Terraform Init
        working-directory: ${{ github.event.inputs.environment || 'env/product-a/dev' }}
        run: |
          set -x
          terraform init

      - name: Terraform Plan
        working-directory: ${{ github.event.inputs.environment || 'env/product-a/dev' }}
        run: |
          set -x
          terraform plan -out=tfplan -input=false